//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.15 at 11:28:52 PM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://cuauh-cabrera.com/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cuauh_cabrera.courses;
